site_name: Coding4Math

pages:
  - Introduzione: index.md
  - Set-up (Mac OS High Sierra): set-up-mac.md
  - Set-up (Windows 10): set-up-windows.md
  # - Set-up (Windows 10): set-up-windows-10.md
  - Shell interattiva: shell-interattiva.md
  - Sintassi di base: sintassi-di-base.md
  - Variabili: variabili.md
  - Operatori: operatori.md
  - Input/Output: input-output.md
  - Costrutti condizionali: decision-making.md
  - Cicli iterativi: cicli-iterativi.md
  - Funzioni: funzioni.md
  - Gestione degli errori: error-handling.md
  - OOP: oop.md
  - Metodi standard: metodi-standard.md
  - Moduli: moduli.md
  - Packages: packages.md
  - Esercitazioni: esercitazioni.md

theme: 
  name: 'material'
  # favicon: 'img/favicon.ico'
  language: 'it'

# site_favicon: docs/img/favicon.ico

plugins: []

markdown_extensions:
  - pymdownx.arithmatex

extra_javascript:
  # - js/mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

copyright: © Copyright 2018, Francesco Sasso.