site_name: Coding4Math

pages:
  - Introduzione: index.md
  - Set-up: set-up.md

theme: 
  name: 'material'
  # favicon: 'img/favicon.ico'
  language: 'it'

# site_favicon: docs/img/favicon.ico

markdown_extensions:
  - pymdownx.arithmatex

extra_javascript:
  # - js/mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

copyright: © Copyright 2018, Francesco Sasso.